BehaviourManagementSystem_MVC/Areas/Admin/Controllers/AnalyzeAntecedentPerceivedController.cs
using BehaviourManagementSystem_MVC.APIIntegration;
using BehaviourManagementSystem_ViewModels.Requests;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace BehaviourManagementSystem_MVC.Area.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(AuthenticationSchemes = "Admin", Policy = "AdminOnly")]
    public class AnalyzeAntecedentPerceivedController : Controller
    {
        private readonly IAntecedentPerceivedAPIClient _IAntecedentPerceivedAPIClient;
        private readonly IToastNotification toastNotification;
        public AnalyzeAntecedentPerceivedController(IAntecedentPerceivedAPIClient IAntecedentOptionAPIClient, IToastNotification toastNotification)
        {
            this.toastNotification = toastNotification;
            _IAntecedentPerceivedAPIClient = IAntecedentOptionAPIClient;
        }
        public async Task<IActionResult> Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            try
            {
                var response = await _IAntecedentPerceivedAPIClient.GetAll();
                if (response.Success == true)
                {
                    return View(response.Result.ToPagedList(pageNumber, pageSize));
                }
            }
            catch (Exception)
            {

                throw;
            }
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateAsync(string content)
        {
            try
            {
                var response = await _IAntecedentPerceivedAPIClient.Create(content);
                if (response.Success == true)
                {
                    toastNotification.AddSuccessToastMessage("Thêm Thành Công!");
                    return RedirectToAction("Index", response.Result);
                }
                else
                {
                    string Message = response.Message;
                    toastNotification.AddErrorToastMessage(Message);
                }
            }
            catch (Exception)
            {

                throw;
            }
            return RedirectToAction("Index");


        }

        public async Task<IActionResult> Edit(string id)
        {
            try
            {
                var response = await _IAntecedentPerceivedAPIClient.Get(id);
                if (response.Success == true)
                {
                    return View(response.Result);
                }
            }
            catch (Exception)
            {

                throw;
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(OptionsRequest request)
        {
            try
            {
                var response = await _IAntecedentPerceivedAPIClient.Update(request);
                if (response.Success == true)
                {
                    toastNotification.AddSuccessToastMessage("Sửa Thành Công!");
                    return RedirectToAction("Index", response.Result);
                }
                else
                {
                    string Message = response.Message;
                    toastNotification.AddErrorToastMessage(Message);
                }
            }
            catch (Exception)
            {

                throw;
            }
            return RedirectToAction("Index");
        }
        [HttpDelete]
        public async Task<IActionResult> DeleteAsync(string id)
        {
            try
            {
                var response = await _IAntecedentPerceivedAPIClient.Delete(id);
                if (response.Success == true)
                {
                    toastNotification.AddSuccessToastMessage("Xóa Thành Công!");
                    return Json(new
                    {
                        status = true
                    });
                }
            }
            catch (Exception)
            {

                throw;
            }
            return RedirectToAction("Index");
        }
    }
}

BehaviourManagementSystem_MVC/Areas/Admin/Views/AnalyzeAntecedentPerceived/Edit.cshtml
@model OptionsRequest
@{
    Layout = null;
}
@*Model Edit*@
<div class="modal modal-EditPerceived" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0">Chỉnh Sửa Trạng Thái Cảm Xúc</h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <form method="post" asp-action="Edit" asp-controller="AnalyzeAntecedentPerceived" asp-area="Admin" asp-route-id="@Model.Id">
                    <div class="form-group">
                        <label>Tên Trạng Thái Cảm Xúc</label>
                        <input asp-for="@Model.Content" autocomplete="off" type="text" class="form-control" required placeholder="Điền Tên Trạng Thái Cảm Xúc..." data-parsley-required-message="Hãy nhập tên trạng thái cảm xúc" />
                    </div>
                    <div class="form-group text-center">
                        <div>
                            <button type="submit" class="btn btn-primary waves-effect waves-light">
                                Sửa
                            </button>
                            <button type="reset" data-dismiss="modal" class="btn btn-secondary waves-effect m-l-5">
                                Hủy
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
@section scripts{
<script src="~/plugins/parsleyjs/parsley.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('form').parsley();
    });
</script>
}

BehaviourManagementSystem_MVC/Areas/Admin/Views/AnalyzeAntecedentPerceived/Index.cshtml
@model X.PagedList.IPagedList<BehaviourManagementSystem_ViewModels.Requests.OptionsRequest>
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@{
    ViewData["Title"] = "Index";
}
@section styles {
    <link href="~/plugins/RWD-Table-Patterns/dist/css/rwd-table.min.css" rel="stylesheet" type="text/css" media="screen">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/plugins/sweet-alert2/sweetalert2.min.css" rel="stylesheet" type="text/css">
}
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <h4 class="page-title">Trạng Thái Cảm Xúc</h4>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/admin">Trang chủ</a></li>
                <li class="breadcrumb-item">Quản lí sự cố</li>
                <li class="breadcrumb-item active">Trạng thái cảm xúc</li>
            </ol>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card m-b-20">
            <div class="card-body">
                <button type="button" data-toggle="modal" data-target=".modal-CreatePerceived" class="btn btn-primary waves-effect waves-light">Thêm</button>
                @if (Model != null)
                {
                    <div class="table-rep-plugin">
                        <div class="table-responsive b-0" data-pattern="priority-columns">
                            <table id="tech-companies-1" class="table table-striped">
                                <thead class="text-center">
                                    <tr>
                                        <th>Số Thứ Tự</th>
                                        <th data-priority="1">Tên Trạng Thái Cảm Xúc</th>
                                        <th data-priority="6">Tùy Chọn</th>

                                    </tr>
                                </thead>
                                <tbody class="text-center">
                                    @for (var i = 0; i < Model.Count; i++)
                                    {
                                        <tr id="perceived-@Model[i].Id">

                                            <td>@Model[i].STT</td>
                                            <td>@Model[i].Content</td>
                                            <td>
                                                <button type="button" data-url="@Url.Action($"Edit/{@Model[i].Id}")" data-toggle="modalEdit" data-target=".modal-EditPerceived" class="btn btn-warning waves-effect waves-light">Sửa</button>
                                                <button type="button" onclick=" deletePerceived('@Model[i].Id')" class="btn btn-danger waves-effect waves-light">Xóa</button>
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                            <span class="show-page-text text-black">Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount</span>
                            @Html.PagedListPager(Model,
                                    page => Url.Action("Index", new { page }),
                                    new PagedListRenderOptions
                                {
                                    DisplayLinkToIndividualPages = true,
                                    DisplayPageCountAndCurrentLocation = false,
                                    MaximumPageNumbersToDisplay = 3,
                                    LiElementClasses = new string[] { "page-item" },
                                        PageClasses = new string[] { "page-link" },
                                })
                        </div>

                    </div>

                }
                else
                {
                    <p class="text-center">Không có dữ liệu</p>
                }
                <div class="modal fade modal-CreatePerceived" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title mt-0">Thêm Trạng Thái Cảm Xúc</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            </div>
                            <div class="modal-body">
                                <form class="" action="/Admin/AnalyzeAntecedentPerceived/Create" method="post">
                                    <div class="form-group">
                                        <label>Tên Trạng Thái Cảm Xúc</label>
                                        <input type="text" autocomplete="off" name="content" class="form-control" required placeholder="Điền Tên Trạng Thái Cảm Xúc..." />
                                    </div>
                                    <div class="form-group text-center">
                                        <div>
                                            <button type="submit" class="btn btn-primary waves-effect waves-light">
                                                Thêm
                                            </button>
                                            <button type="reset" data-dismiss="modal" class="btn btn-secondary waves-effect m-l-5">
                                                Hủy
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div>
                <div id="PlaceHolder"></div>
            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->
@section scripts {
    <script src="~/plugins/RWD-Table-Patterns/dist/js/rwd-table.min.js"></script>
    <script src="~/plugins/sweet-alert2/sweetalert2.min.js"></script>
    <script src="~/plugins/parsleyjs/parsley.min.js"></script>
    @*<script src="~/js/sweet-alert.init.js"></script>*@
    <script>
        //Warning Message
        function deletePerceived(id) {
            swal({
                title: 'Bạn đã chắc chắn xóa?',
                text: "",
                type: '',
                showCancelButton: true,
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger m-l-10',
                confirmButtonText: 'Có',
                cancelButtonText: "Không"
            }).then(function () {
                $.ajax({
                    url: "AnalyzeAntecedentPerceived/delete",
                    data: { "id": id },
                    type: "DELETE",
                    success: function (result) {
                        if (result.status == true) {
                            
                                $("#perceived-" + id).remove();
                        }
                    }
                })
            })
        }

        $(function () {
            var PlaceHolder = $('#PlaceHolder');
            $('button[data-toggle="modalEdit"]').click(function (event) {
                var url = $(this).data('url');
                var decodedUrl = decodeURIComponent(url);
                $.get(decodedUrl).done(function (data) {
                    PlaceHolder.html(data);
                    PlaceHolder.find('.modal-EditPerceived').modal('show');
                })
            })
        })

    </script>

}